### PR TITLE
Single file decompress

### LINKED ISSUE #44: Mark is not supported
I am trying to decompress a `.gz` file using the provided tasks (no tar).

Unfotunately, it blows:

```
...
                                             cljsjs.impl.decompress/decompress-file               decompress.clj:   26
                                             cljsjs.impl.decompress/decompress-file               decompress.clj:   29
                                                                                ...                                   
                                            cljsjs.impl.decompress/unpackage-stream               decompress.clj:   20
                                            cljsjs.impl.decompress/unpackage-stream               decompress.clj:   24
                                                                                ...                                   
org.apache.commons.compress.archivers.ArchiveStreamFactory.createArchiveInputStream    ArchiveStreamFactory.java:  290
java.lang.IllegalArgumentException: Mark is not supported.
        clojure.lang.ExceptionInfo: Mark is not supported.
```

Debugging it, basically the problem is that [this guy](https://github.com/cljsjs/boot-cljsjs/blob/master/src/cljsjs/impl/decompress.clj#L12) creates a `org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream` which does not support marking, which is weird.

The `ArchiveStreamFactory` has the requirement, see [here](https://apache.googlesource.com/commons-compress/+/zip64/src/main/java/org/apache/commons/compress/archivers/ArchiveStreamFactory.java#194).

Thoughts?

### PR DESCRIPTION
**Pull request by arichiardi**
This fixes #44.

Packages tried with it:
 
 * my own which contains a single-file `.gz` archive
 * `react-google-maps` (huge one)
 * `quill` which contains a `tar.gz`
 * `papaparse` which contains a `tar.gz`

### CODE REVIEW

File: src/cljsjs/impl/decompress.clj [hunk 1]
```diff
@@ -1,40 +1,55 @@
...
+                          (io/make-parents target)
+                          ;; After .getNextEntry the stream points to the specific archive entry
+                          (io/copy is target)
+                          (recur (inc i) (.getNextEntry is)))
+                        (recur i (.getNextEntry is)))
+                      i))]
+        (util/info (format "Extracted %d files\n" count)))
+      (let [target (io/file out-dir (.getUncompressedFilename @file-name-util (.getName (io/file in))))]
+        (io/make-parents target)
+        (io/copy is target)))))
```
Comment (Deraen) [inline src/cljsjs/impl/decompress.clj]: Add `(util/info (format "Extracted 1 file\n"))` here to match logging on the other branch.

File: src/cljsjs/impl/decompress.clj [hunk 2]
```diff
@@ -1,40 +1,55 @@
...
             [clojure.java.io     :as io])
-  (:import [org.apache.commons.compress.compressors CompressorStreamFactory]
+  (:import [org.apache.commons.compress.compressors CompressorStreamFactory FileNameUtil ]
            [org.apache.commons.compress.archivers ArchiveStreamFactory]))
 
+(def file-name-util (delay (FileNameUtil. {".gz" ""
+                                           ".xz" ""
+                                           ".bzip2" ""
+                                           ".bz2" ""
+                                           ".tgz" ".tar"
```
Comment (Deraen) [inline src/cljsjs/impl/decompress.clj]: tar files should support marking, so there are probably unncessary

Comment (arichiardi) [inline src/cljsjs/impl/decompress.clj]: shall we leave it just to be sure?
